name: Manually Trigger A Job
on:
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - error
      tests_against_pr:
        description: 'Pull request to run the tests'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
      notify:
        description: 'Notify me'
        type: string
        default: ${{ github.triggering_actor }}
jobs:
  trigger_job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Print something'
        run: echo "Nice to meet you"
        run: echo "See you again"
