name: Manually Trigger A Job
on:
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log Level'
        required: true
        default: 'WARNING'
        type: choice
        options:
          - INFO
          - WARNING
          - ERROR
      environment:
        description: 'Environment to run tests against'
        required: true
        default: development
        type: choice
        options:
          - development
          - staging
          - production
      site_url:
        description: 'Site URL'
        required: true
        default: 'https://gorest.co.in/public/v2/'
        type: string
      test_branch:
        description: 'E2E test branch'
        required: true
        default: main
        type: string
      test_type:
        description: 'Test type'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - api
          - e2e
          - visual
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        run: echo "Checkout to branch: ${{ github.ref_name }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ input.test_branch }}
      - name: Setup npm packages
        run: npm i
      - name: Run E2E regression tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          # parallel: true
          command: npm run cy:run:${{ inputs.environment }}
        env:
          # Get the short ref name of the branch that triggered the workflow run
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          CYPRESS_TOKEN: ${{ secrets.TOKEN }}
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-regression-test
          path: ./cypress/reports/html/
          retention-days: 5
