name: Trigger Slack Notification

on:
  pull_request:
    types: [opened]

jobs:
  trigger-slack-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Slack Notification Workflow
      uses: actions/github-script@v6
      with:
        script: |
          const workflow = 'pr-slack-notification.yml';
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const ref = context.ref;

          await github.actions.createWorkflowDispatch({
            owner,
            repo,
            workflow_id: workflow,
            ref,
          });
      if: always()
