name: E2E - Smoke test
on:
  pull_request:
    types: [opened, reopened]
jobs:
  notify:
    name: PR notification
    runs-on: ubuntu-latest
    steps:
      - name: Send slack notification
        uses: slackapi/slack-github-action@v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "title": ${{ toJson(github.event.pull_request.title) }},
              "author": ${{ toJson(github.event.pull_request.user.login) }},
              "link": ${{ toJson(github.event.pull_request.html_url) }}
            }
