name: Send slack notification
on:
  pull_request:
    types: [opened, reopened]
jobs:
  notify:
    name: PR notification
    runs-on: ubuntu-latest
    steps:
      - name: Send slack notification
        uses: slackapi/slack-github-action@v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          channel: '#qa-notify'
        if: always()
