name: Send slack notification
on:
  pull_request:
    types: [opened, reopened]
jobs:
  notify:
    name: PR notification
    runs-on: ubuntu-latest
    steps:
      - name: Post a message in a channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Pull request opened by ${{ github.event.pull_request.user.login }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Danny Torrence left the following review for your property:"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "<https://example.com|*Overlook Hotel*> :star: \n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
                accessory:
                  type: "image"
                  image_url: "https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/d3/72/5c/d3725c8f-c642-5d69-1904-aa36e4297885/source/256x256bb.jpg"
                  alt_text: "Haunted hotel image"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Average Rating*: 1.0"
