name: Send slack notification
on:
  pull_request:
    types: [opened, reopened]
jobs:
  notify:
    name: PR notification
    runs-on: ubuntu-latest
    steps:
      - name: Send slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
        if: always()
