name: E2E - Smoke test
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened]
    branches:
      - develop
  workflow_dispatch: {}
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      fail-fast: false
      matrix:
       containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup npm packages
        run: npm i
      - name: Run E2E smoke tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          # parallel: true
          env: grepTags=smoke
          command: npm run cy:run:dev
          tag: tags
        env:
          # Get the short ref name of the branch that triggered the workflow run
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          CYPRESS_TOKEN: ${{ secrets.TOKEN }}
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports-regression-test
          path: ./cypress/reports/html/
          retention-days: 5
