name: Run tests against a PR
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup npm packages
        run: npm i
      - name: Run E2E smoke tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          env: grepTags=smoke
          command: npm run cy:run:dev
          tag: tags
        env:
          # Get the short ref name of the branch that triggered the workflow run
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          CYPRESS_TOKEN: ${{ secrets.TOKEN }}
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: |
          contains(github.event.pull_request.labels.*.name, 'smoke-test')
